export enum NotificationType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_SUCCESS = 'ORDER_SUCCESS',
  DEBT_ORDER_REQUEST = 'DEBT_ORDER_REQUEST',
  DEBT_SERVICE_REQUEST = 'DEBT_SERVICE_REQUEST',
  CUSTOMER_REGISTERED = 'CUSTOMER_REGISTERED',
  CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS',
  CUSTOMER_LOGIN_FAILED = 'CUSTOMER_LOGIN_FAILED',
  CUSTOMER_PASSWORD_RESET = 'CUSTOMER_PASSWORD_RESET',
  CUSTOMER_PROFILE_UPDATED = 'CUSTOMER_PROFILE_UPDATED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  STOCK_ALERT = 'STOCK_ALERT',
  CART_REMINDER = 'CART_REMINDER',
  PRODUCT_REVIEW_REQUESTED = 'PRODUCT_REVIEW_REQUESTED',
  PROMOTIONAL_EMAIL_SENT = 'PROMOTIONAL_EMAIL_SENT',
  PROMOTION_CREATED = 'PROMOTION_CREATED',
  MARKETING_CAMPAIGN_LAUNCHED = 'MARKETING_CAMPAIGN_LAUNCHED',
  SOCIAL_MEDIA_AD_PUBLISHED = 'SOCIAL_MEDIA_AD_PUBLISHED',
  EMAIL_SUBSCRIPTION_CONFIRMED = 'EMAIL_SUBSCRIPTION_CONFIRMED',
  LEAD_GENERATION_FORM_SUBMITTED = 'LEAD_GENERATION_FORM_SUBMITTED',
  ERROR_SYSTEM_FAILURE = 'ERROR_SYSTEM_FAILURE',
  ERROR_PAYMENT_PROCESSING = 'ERROR_PAYMENT_PROCESSING',
  ERROR_ORDER_PROCESSING = 'ERROR_ORDER_PROCESSING',
  MEMBERSHIP_UPGRADED = 'MEMBERSHIP_UPGRADED',
  MEMBERSHIP_DOWNGRADED = 'MEMBERSHIP_DOWNGRADED',
  ZNS_KIOTVIET_ORDER = 'ZNS_KIOTVIET_ORDER',
  ZNS_KIOTVIET_DEBT = 'ZNS_KIOTVIET_DEBT',
}

export enum NotificationStatus {
  ACTIVE = 'ACTIVE',
  IN_ACTIVE = 'IN_ACTIVE',
}

export interface Notification {
  id?: string;
  title?: string;
  message?: string;
  description?: string;
  type?: NotificationType;
  read?: boolean;
  status?: NotificationStatus;
  relatedId?: string;
  orderId?: number;
  eventType?: string;
  createdDate?: string;
}
